# Generated by Django 5.0 on 2024-01-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDisplay', models.CharField(max_length=50)),
                ('nameHandle', models.CharField(max_length=50)),
                ('postText', models.CharField(max_length=280)),
                ('datePosted', models.DateField()),
            ],
        ),
    ]
