# Generated by Django 5.0 on 2024-01-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='dateTimePosted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
