# Generated by Django 5.0 on 2024-01-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_status_datetimeposted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=280, null=True),
        ),
    ]
