# Generated by Django 5.0 on 2024-01-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='media1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
