# Generated by Django 5.0 on 2024-01-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
