# Generated by Django 5.0 on 2024-02-01 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_user_datetimejoined_alter_status_datetimeposted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='viewer',
            new_name='viewerID',
        ),
    ]
