# Generated by Django 5.0 on 2024-02-08 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_viewer_like_viewerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='replyID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.status'),
        ),
    ]
